// This file contains the static student data from the provided spreadsheet

export type StudentData = {
  "First Name": string
  "Last Name": string
  "Full Name": string
  "Date of Birth": string
  Department: string
  "ID No": string
  Address: string
  "Blood Group": string
  Email: string
}

export const studentData: StudentData[] = [
  {
    "First Name": "Arun",
    "Last Name": "Sekar",
    "Full Name": "Arun Sekar",
    "Date of Birth": "2-10-2005",
    Department: "BCA",
    "ID No": "BCA9492",
    Address: "365, Kamarajar Road, Adyar",
    "Blood Group": "A-",
    Email: "arunsekar37@college.edu",
  },
  {
    "First Name": "Ashok",
    "Last Name": "Ganesan",
    "Full Name": "Ashok Ganesan",
    "Date of Birth": "7-8-2004",
    Department: "BCA",
    "ID No": "BCA9051",
    Address: "484, Gandhi Street, Adyar",
    "Blood Group": "AB+",
    Email: "ashokganesan23@college.edu",
  },
  {
    "First Name": "Ashok",
    "Last Name": "Ramanan",
    "Full Name": "Ashok Ramanan",
    "Date of Birth": "24-1-2004",
    Department: "BCA",
    "ID No": "BCA7831",
    Address: "72, Gandhi Street, T.Nagar",
    "Blood Group": "A-",
    Email: "ashokramanan36@college.edu",
  },
  {
    "First Name": "Bharath",
    "Last Name": "Kumar",
    "Full Name": "Bharath Kumar",
    "Date of Birth": "17-1-2005",
    Department: "BCA",
    "ID No": "BCA6088",
    Address: "468, Gandhi Street, Besant Nagar",
    "Blood Group": "B+",
    Email: "bharathkumar89@college.edu",
  },
  {
    "First Name": "Charan",
    "Last Name": "Vel",
    "Full Name": "Charan Vel",
    "Date of Birth": "20-4-2005",
    Department: "BCA",
    "ID No": "BCA4057",
    Address: "481, Kamarajar Road, Adyar",
    "Blood Group": "AB-",
    Email: "charanvel60@college.edu",
  },
  {
    "First Name": "Deepak",
    "Last Name": "Raja",
    "Full Name": "Deepak Raja",
    "Date of Birth": "25-4-2005",
    Department: "BCA",
    "ID No": "BCA9226",
    Address: "500, Thiruvallur",
    "Blood Group": "B+",
    Email: "deepakraja44@college.edu",
  },
  {
    "First Name": "Deepak",
    "Last Name": "Vel",
    "Full Name": "Deepak Vel",
    "Date of Birth": "22-10-2005",
    Department: "BCA",
    "ID No": "BCA3156",
    Address: "174, Kamarajar Road, Besant Nagar",
    "Blood Group": "B-",
    Email: "deepakvel40@college.edu",
  },
  {
    "First Name": "Dinesh",
    "Last Name": "Muthu",
    "Full Name": "Dinesh Muthu",
    "Date of Birth": "6-7-2004",
    Department: "BCA",
    "ID No": "BCA8462",
    Address: "278, MG Road, Chennai",
    "Blood Group": "O+",
    Email: "dineshmuthu62@college.edu",
  },
  {
    "First Name": "Elango",
    "Last Name": "Ganesan",
    "Full Name": "Elango Ganesan",
    "Date of Birth": "1-7-2005",
    Department: "BCA",
    "ID No": "BCA7549",
    Address: "189, Rajaji Road, Velachery",
    "Blood Group": "B+",
    Email: "elangoganesan72@college.edu",
  },
  {
    "First Name": "Ezhil",
    "Last Name": "Raja",
    "Full Name": "Ezhil Raja",
    "Date of Birth": "24-4-2004",
    Department: "BCA",
    "ID No": "BCA9605",
    Address: "342, MG Road, Tiruvanmiyur",
    "Blood Group": "AB+",
    Email: "ezhilraja96@college.edu",
  },
  {
    "First Name": "Farhan",
    "Last Name": "Mahadevan",
    "Full Name": "Farhan Mahadevan",
    "Date of Birth": "25-11-2005",
    Department: "BCA",
    "ID No": "BCA6750",
    Address: "192, Anna Salai, Chennai",
    "Blood Group": "O+",
    Email: "farhanmahadevan12@college.edu",
  },
  {
    "First Name": "Gokul",
    "Last Name": "Iyer",
    "Full Name": "Gokul Iyer",
    "Date of Birth": "28-10-2004",
    Department: "BCA",
    "ID No": "BCA4148",
    Address: "243, Gandhi Street, Adyar",
    "Blood Group": "AB+",
    Email: "gokuliyer54@college.edu",
  },
  {
    "First Name": "Jagadeesh",
    "Last Name": "Kumar",
    "Full Name": "Jagadeesh Kumar",
    "Date of Birth": "4-6-2005",
    Department: "BCA",
    "ID No": "BCA3616",
    Address: "335, Anna Salai, Thiruvanmiyur",
    "Blood Group": "AB+",
    Email: "jagadeeshkumar52@college.edu",
  },
  {
    "First Name": "Jagan",
    "Last Name": "Ramanan",
    "Full Name": "Jagan Ramanan",
    "Date of Birth": "27-4-2005",
    Department: "BCA",
    "ID No": "BCA6298",
    Address: "370, Rajaji Road, T.Nagar",
    "Blood Group": "A+",
    Email: "jaganramanan78@college.edu",
  },
  {
    "First Name": "Jeeva",
    "Last Name": "Ganesan",
    "Full Name": "Jeeva Ganesan",
    "Date of Birth": "24-4-2004",
    Department: "BCA",
    "ID No": "BCA9214",
    Address: "47, MG Road, Salem",
    "Blood Group": "A-",
    Email: "jeevaganesan79@college.edu",
  },
  {
    "First Name": "Jeeva",
    "Last Name": "Vel",
    "Full Name": "Jeeva Vel",
    "Date of Birth": "24-8-2005",
    Department: "BCA",
    "ID No": "BCA6917",
    Address: "407, Gandhi Street, Adyar",
    "Blood Group": "A-",
    Email: "jeeavel13@college.edu",
  },
  {
    "First Name": "Karthick",
    "Last Name": "T",
    "Full Name": "Karthick T",
    "Date of Birth": "15-04-2005",
    Department: "BCA",
    "ID No": "BCA9999",
    Address: "456, Kamarajar Road, Omr",
    "Blood Group": "O+",
    Email: "karthick.t@college.edu",
  },
  {
    "First Name": "Karthik",
    "Last Name": "Eswar",
    "Full Name": "Karthik Eswar",
    "Date of Birth": "17-6-2004",
    Department: "BCA",
    "ID No": "BCA1774",
    Address: "291, Rajaji Road, Mylapore",
    "Blood Group": "AB+",
    Email: "karthikiyerr84@college.edu",
  },
  {
    "First Name": "Kishore",
    "Last Name": "Vel",
    "Full Name": "Kishore Vel",
    "Date of Birth": "4-11-2004",
    Department: "BCA",
    "ID No": "BCA8936",
    Address: "264, Periyar Street, Besant Nagar",
    "Blood Group": "B-",
    Email: "kishorevel48@college.edu",
  },
  {
    "First Name": "Lakshman",
    "Last Name": "Ramanan",
    "Full Name": "Lakshman Ramanan",
    "Date of Birth": "6-1-2004",
    Department: "BCA",
    "ID No": "BCA2558",
    Address: "197, Kamarajar Road, Omr",
    "Blood Group": "O-",
    Email: "lakshmanramanan90@college.edu",
  },
  {
    "First Name": "Madhan",
    "Last Name": "Vel",
    "Full Name": "Madhan Vel",
    "Date of Birth": "17-11-2004",
    Department: "BCA",
    "ID No": "BCA4538",
    Address: "344, Anna Salai, Kodambakkam",
    "Blood Group": "AB+",
    Email: "madhanvel42@college.edu",
  },
  {
    "First Name": "Manoj",
    "Last Name": "Raj",
    "Full Name": "Manoj Raj",
    "Date of Birth": "4-5-2005",
    Department: "BCA",
    "ID No": "BCA4993",
    Address: "33, Kamarajar Road, Adyar",
    "Blood Group": "A+",
    Email: "manojraj98@college.edu",
  },
  {
    "First Name": "Muthu",
    "Last Name": "Krishnan",
    "Full Name": "Muthu Krishnan",
    "Date of Birth": "23-3-2005",
    Department: "BCA",
    "ID No": "BCA1172",
    Address: "115, Gandhi Street, Adyar",
    "Blood Group": "A+",
    Email: "muthukrishnan15@college.edu",
  },
  {
    "First Name": "Muthu",
    "Last Name": "Raj",
    "Full Name": "Muthu Raj",
    "Date of Birth": "8-10-2004",
    Department: "BCA",
    "ID No": "BCA1339",
    Address: "114, MG Road, Tiruvanmiyur",
    "Blood Group": "B-",
    Email: "muthuraj89@college.edu",
  },
  {
    "First Name": "Nanditha",
    "Last Name": "G",
    "Full Name": "Nanditha G",
    "Date of Birth": "03-03-2005",
    Department: "BCA",
    "ID No": "BCA9998",
    Address: "123, Anna Salai, Chennai",
    "Blood Group": "AB-",
    Email: "nanditha.g@college.edu",
  },
  {
    "First Name": "Omprakash",
    "Last Name": "Baskar",
    "Full Name": "Omprakash Baskar",
    "Date of Birth": "10-9-2004",
    Department: "BCA",
    "ID No": "BCA4763",
    Address: "277, Thiruvallur",
    "Blood Group": "O+",
    Email: "omprakashbaskar62@college.edu",
  },
  {
    "First Name": "Prakash",
    "Last Name": "Krishnan",
    "Full Name": "Prakash Krishnan",
    "Date of Birth": "4-4-2005",
    Department: "BCA",
    "ID No": "BCA9890",
    Address: "226, Thiruvallur",
    "Blood Group": "O+",
    Email: "prakashkrishnan37@college.edu",
  },
  {
    "First Name": "Prakash",
    "Last Name": "Muthu",
    "Full Name": "Prakash Muthu",
    "Date of Birth": "11-12-2004",
    Department: "BCA",
    "ID No": "BCA9917",
    Address: "22, MG Road, Coimbatore",
    "Blood Group": "AB-",
    Email: "prakashmuthu40@college.edu",
  },
  {
    "First Name": "Prakash",
    "Last Name": "Raj",
    "Full Name": "Prakash Raj",
    "Date of Birth": "1-5-2005",
    Department: "BCA",
    "ID No": "BCA3217",
    Address: "161, MG Road, Tiruvanmiyur",
    "Blood Group": "O+",
    Email: "prakashraj75@college.edu",
  },
  {
    "First Name": "Prakash",
    "Last Name": "Vasan",
    "Full Name": "Prakash Vasan",
    "Date of Birth": "4-3-2005",
    Department: "BCA",
    "ID No": "BCA7738",
    Address: "282, Periyar Street, Omr",
    "Blood Group": "O+",
    Email: "prakashvasan99@college.edu",
  },
  {
    "First Name": "Quadir",
    "Last Name": "Muthu",
    "Full Name": "Quadir Muthu",
    "Date of Birth": "16-12-2005",
    Department: "BCA",
    "ID No": "BCA3020",
    Address: "57, Thiruvalluvur Nagar, Adyar",
    "Blood Group": "AB-",
    Email: "quadirmuthu56@college.edu",
  },
  {
    "First Name": "Quadir",
    "Last Name": "Narayanan",
    "Full Name": "Quadir Narayanan",
    "Date of Birth": "9-10-2004",
    Department: "BCA",
    "ID No": "BCA6183",
    Address: "236, Rajaji Road, Tiruvanmiyur",
    "Blood Group": "B-",
    Email: "quadirnarayanan76@college.edu",
  },
  {
    "First Name": "Ramesh",
    "Last Name": "Baskar",
    "Full Name": "Ramesh Baskar",
    "Date of Birth": "4-11-2005",
    Department: "BCA",
    "ID No": "BCA4039",
    Address: "283, Gandhi Street, Besant Nagar",
    "Blood Group": "B+",
    Email: "rameshbaskar89@college.edu",
  },
  {
    "First Name": "Ramesh",
    "Last Name": "Raja",
    "Full Name": "Ramesh Raja",
    "Date of Birth": "17-9-2004",
    Department: "BCA",
    "ID No": "BCA8278",
    Address: "33, Thiruvalluvur Nagar, Adyar",
    "Blood Group": "A+",
    Email: "rameshraja49@college.edu",
  },
  {
    "First Name": "Ramesh",
    "Last Name": "Srinivasan",
    "Full Name": "Ramesh Srinivasan",
    "Date of Birth": "13-5-2004",
    Department: "BCA",
    "ID No": "BCA1458",
    Address: "63, Nehru Nagar, Mylapore",
    "Blood Group": "O-",
    Email: "rameshsrinivasan10@college.edu",
  },
  {
    "First Name": "Rithesh",
    "Last Name": "Murugan",
    "Full Name": "Rithesh Murugan",
    "Date of Birth": "21-6-2005",
    Department: "BCA",
    "ID No": "BCA3312",
    Address: "403, Periyar Street, Besant Nagar",
    "Blood Group": "B+",
    Email: "ritheshmurugan34@college.edu",
  },
  {
    "First Name": "Rithesh",
    "Last Name": "Srinivasan",
    "Full Name": "Rithesh Srinivasan",
    "Date of Birth": "10-8-2004",
    Department: "BCA",
    "ID No": "BCA3818",
    Address: "466, Thiruvallur",
    "Blood Group": "B-",
    Email: "ritheshsrinivasan88@college.edu",
  },
  {
    "First Name": "Rithesh",
    "Last Name": "Vel",
    "Full Name": "Rithesh Vel",
    "Date of Birth": "11-8-2004",
    Department: "BCA",
    "ID No": "BCA9648",
    Address: "12, Nehru Nagar, Tiruvanmiyur",
    "Blood Group": "A-",
    Email: "ritheshvel17@college.edu",
  },
  {
    "First Name": "Santhosh",
    "Last Name": "Devan",
    "Full Name": "Santhosh Devan",
    "Date of Birth": "7-4-2005",
    Department: "BCA",
    "ID No": "BCA5643",
    Address: "161, MG Road, Erode",
    "Blood Group": "A+",
    Email: "santhoshdevan35@college.edu",
  },
  {
    "First Name": "Santhosh",
    "Last Name": "Natesan",
    "Full Name": "Santhosh Natesan",
    "Date of Birth": "24-2-2004",
    Department: "BCA",
    "ID No": "BCA5116",
    Address: "229, Periyar Street, Adyar",
    "Blood Group": "AB-",
    Email: "santhoshnatesan25@college.edu",
  },
  {
    "First Name": "Sathish",
    "Last Name": "Vel",
    "Full Name": "Sathish Vel",
    "Date of Birth": "13-5-2005",
    Department: "BCA",
    "ID No": "BCA6479",
    Address: "459, Gandhi Street, Besant Nagar",
    "Blood Group": "B+",
    Email: "sathishvel39@college.edu",
  },
  {
    "First Name": "Shankar",
    "Last Name": "Sundar",
    "Full Name": "Shankar Sundar",
    "Date of Birth": "13-3-2004",
    Department: "BCA",
    "ID No": "BCA2071",
    Address: "304, Anna Salai, Erode",
    "Blood Group": "AB+",
    Email: "shankarsundar57@college.edu",
  },
  {
    "First Name": "Suresh",
    "Last Name": "Raj",
    "Full Name": "Suresh Raj",
    "Date of Birth": "17-3-2004",
    Department: "BCA",
    "ID No": "BCA3238",
    Address: "33, Anna Salai, Tiruvanmiyur",
    "Blood Group": "A-",
    Email: "sureshraj88@college.edu",
  },
  {
    "First Name": "Suresh",
    "Last Name": "Sekar",
    "Full Name": "Suresh Sekar",
    "Date of Birth": "1-6-2004",
    Department: "BCA",
    "ID No": "BCA6482",
    Address: "9, Nehru Nagar, Karur",
    "Blood Group": "O-",
    Email: "sureshsekar57@college.edu",
  },
  {
    "First Name": "Tamil",
    "Last Name": "Devan",
    "Full Name": "Tamil Devan",
    "Date of Birth": "24-12-2004",
    Department: "BCA",
    "ID No": "BCA2267",
    Address: "283, Periyar Street, Adyar",
    "Blood Group": "A-",
    Email: "tamildevan43@college.edu",
  },
  {
    "First Name": "Tamil",
    "Last Name": "Prasad",
    "Full Name": "Tamil Prasad",
    "Date of Birth": "17-5-2005",
    Department: "BCA",
    "ID No": "BCA5361",
    Address: "252, MG Road, Thoraipakkam",
    "Blood Group": "B+",
    Email: "tamilprasad39@college.edu",
  },
  {
    "First Name": "Tamil",
    "Last Name": "Raj",
    "Full Name": "Tamil Raj",
    "Date of Birth": "18-9-2005",
    Department: "BCA",
    "ID No": "BCA5199",
    Address: "446, Gandhi Street, Besant Nagar",
    "Blood Group": "B+",
    Email: "tamilraj60@college.edu",
  },
  {
    "First Name": "Tamil",
    "Last Name": "Vel",
    "Full Name": "Tamil Vel",
    "Date of Birth": "26-4-2005",
    Department: "BCA",
    "ID No": "BCA9485",
    Address: "496, Thiruvallur",
    "Blood Group": "B+",
    Email: "tamilvel52@college.edu",
  },
  {
    "First Name": "Venkat",
    "Last Name": "Mahadevan",
    "Full Name": "Venkat Mahadevan",
    "Date of Birth": "24-6-2004",
    Department: "BCA",
    "ID No": "BCA3672",
    Address: "380, Anna Salai, Tiruvanmiyur",
    "Blood Group": "O+",
    Email: "venkatmahadevan66@college.edu",
  },
  {
    "First Name": "Yogesh",
    "Last Name": "Murugan",
    "Full Name": "Yogesh Murugan",
    "Date of Birth": "20-5-2004",
    Department: "BCA",
    "ID No": "BCA1140",
    Address: "446, Thiruvallur",
    "Blood Group": "AB+",
    Email: "yogeshmurugan46@college.edu",
  },
  {
    "First Name": "Yogesh",
    "Last Name": "Vasan",
    "Full Name": "Yogesh Vasan",
    "Date of Birth": "10-2-2004",
    Department: "BCA",
    "ID No": "BCA7496",
    Address: "329, Thiruvallur Nagar, Besant Nagar",
    "Blood Group": "B-",
    Email: "yogeshvasan40@college.edu",
  },
  {
    "First Name": "Yogesh",
    "Last Name": "Vel",
    "Full Name": "Yogesh Vel",
    "Date of Birth": "3-1-2004",
    Department: "BCA",
    "ID No": "BCA5919",
    Address: "330, Periyar Street, Omr",
    "Blood Group": "O-",
    Email: "yogeshvel94@college.edu",
  },
]

